### PR TITLE
fix: Fix the exports for the package by switching build tool to `tsup`

### PR DESCRIPTION
**Pull request by csandman**
Hey all at the seatsio team! I'm really happy you made the switch to TypeScript! We had to define our own types previously which was a real pain haha. However, I noticed a few issues with your package setup, so I figured I'd take a stab at fixing them! The biggest issue is that you don't have the `"type"` field set in the package.json. Without this being set, it defaults to the default of `"type": "commonjs"`. This is not a problem on it's own, however your compiled JS files all use the `import` syntax specific to ES Modules. When a project attempts to import these, it expects to see them using the `require` syntax, which ends up erroring out:

image

This probably doesn't happen in all environments, but it is happening for mine which is using Next.js v13.4.5.

If you take a look at arethetypeswrong, you can see that the config is invalid: https://arethetypeswrong.github.io/?p=%40seatsio%2Fseatsio-react%4014.1.0

image

Anyway, there are a couple solutions for this, but the approach I implemented uses the build tool [`tsup`](https://github.com/egoist/tsup). It is based on the incredibly fast `esbuild`, and requires very minimal config to set up. It also outputs the proper compiled files for both CommonJS and ES Modules, using the proper `.mjs` file extension for ESM files. This way projects can use whichever it needs based on it's settings. I know introducing a new bundling system is a relatively big change, but it really is the easiest way to get the desired results. Let me know what you think!

I also added the `"exports"` field, for use with projects using a newer node/typescript setup.

Also, here is the updated arethetypeswrong results after these changes:

image

---

One other issue I had was that none of the types used in this package are exported. This is kind of frustrating when using this package, as I had to install `@seatsio/seatsio-types` alongside this package to access them. I tried installing them, but I had compatibility issues everywhere, as this package isn't using the latest version of your types package. The only way to solve this was to install the exact version of the types package that this package depends on.

A very simple solution to this problem was just to add an export line to the `index.ts` file:

```ts
export type * from '@seatsio/seatsio-types';
```

This allows projects to import whichever types it needs directly from this project without dealing with the extra dependency!

While I was at it, I also updated the types package version to the latest, `v2.0.0`. I don't see why this would be problematic, but let me know if it is, and I can undo it!

---

Also, the `.DS_Store` file in the package was bugging me so I added it to the .gitignore and removed it haha. Hope this is ok!

---

Please consider this PR and let me know if I need to make any changes to get this merged in! I can't really use the v14 in my project until the exports are fixed

### CODE REVIEW

**Comment by csandman** [comment]
On a side note, I also saw that the `state` key isn't available on the `SeatingChart` type. You yourselves are casting the type of your `chart` object to any in order to use the `state` key. My team is also using this object key in our own project, and it would be great if you guys could add that key to your `SeatingChart` object so we can avoid casting it. I'd put up a PR for it myself but it appears that your types repo isn't public?

**Comment by mortendevold** [comment]
Hi csandman,

I really appreciate the detailed explanation of the problems with the package, and taking the time to make this pull request to fix it. Your changes look good to me, so I'll approve.

Regarding your use of the `state` property, could you tell me how you are using it? It's not something we've intended to expose, but I'm interested to hear if we perhaps should do so.

**Comment by csandman** [comment]
> Regarding your use of the `state` property, could you tell me how you are using it? It's not something we've intended to expose, but I'm interested to hear if we perhaps should do so.

Sure! So it was my coworker who originally added some code that used this property, but I'll try my best to explain what he used it for.

To preface this, when my team implements this package, we try our best to not change the props that we pass into the chart. We use the props for the initial render state, and the `selectObjects` and `deselctObjects` APIs for any external modification we need to do after the initial render. We do this to ensure that the chart doesn't fully re-initialize based on our selected objects changing as that isn't the best user experience. In order to accomplish this, we keep our initial `selectedObjects` prop in a state value that we don't generally update.

However, when using Next.js we occasionally run into this issue when navigating between pages where the chart is destroyed and never re-initialized. As far as I can tell, it sometimes happen if you click the browser back button to navigate off the chart, and browser forward again quickly enough. I'm not sure what is happening here exactly, and this might be better off as a new issue on it's own (I can try making a minimal reproduction of it if you want). My coworker's solution to this issue was to look at that `state` property though, and if it is coming back as `DESTROYED`, update a `key` prop on the chart to trigger it to rerender. Here is a piece of the code he's been using for this:

```tsx
const getInitialState = (
  props: Pick<ChartState, 'initialSelectedSeats'>,
): ChartState => {
  const { initialSelectedSeats } = props;

  return {
    instance: Date.now(),
    initialSelectedSeats,
  };
};

// const SeatMapWrapper = () => {

  const [state, setState] = useState(() =>
    getInitialState({ initialSelectedSeats: selectedSeatsioSeats }),
  );
  const { instance, initialSelectedSeats } = state;
  const getSelectedSeatsioSeats = useRefGetter(selectedSeatsioSeats);

  const reinitializeChartState = useCallback(() => {
    // Resetting the chart state causes the chart to rerender, resize to the new viewport height, and reinitialize selections.
    // This makes sure that the chart is always current and fitted to the window as the user resizes the browser.
    setState(
      getInitialState({
        initialSelectedSeats: getSelectedSeatsioSeats(),
      }),
    );
  }, [getSelectedSeatsioSeats]);

  const handleRenderStarted = useCallback(
    (chart: SeatingChart) => {
      // eslint-disable-next-line no-param-reassign
      chartRef.current = chart;

      // When quickly navigating forward and back, sometimes the chart gets into an unstable state and fails to render.
      // This may be related to Next.js page caching, but just to be sure we have this fallback so no users encounter this issue.
      // TODO: this resolves an important user-facing bug, but we should look for a nicer way to handle this.
      setTimeout(() => {
        if (chart.state === 'DESTROYED') {
          reinitializeChartState();
        }
      }, 50);
    },
    [chartRef, reinitializeChartState],
  );

  return (
    <SeatsioSeatingChart
      key={instance}
      // ...
    />
  )
```

This might be a bigger underlying issue with a better solution (we could be doing something wrong as well), but I figured I'd let you know how we're handling things!

**Comment by csandman** [comment]
Also one other question! Where is your types package published from? Is it coming from your [DefinitelyTyped](https://github.com/seatsio/DefinitelyTyped/tree/master/types/seatsio/lib) fork? Otherwise I'm not seeing a types package anywhere in your org, unless it's private.

**Comment by mortendevold** [comment]
Thanks for the explanation, if you're able to set up a minimal reproduction that would be great. Then we can try to see if it's something on our end. Regarding types, they are shipped from a private repo for now. That may change in the future.

**Comment by csandman** [comment]
> Thanks for the explanation, if you're able to set up a minimal reproduction that would be great.

Yeah I'll give that a shot when I have time. The more I think about this, the more I think it probably is an issue with this package having conflicting rendering states. I'm not sure what part it might be related to yet, but I was looking at the rendering code and this part seems a bit odd to me: https://github.com/seatsio/seatsio-react/blob/master/src/main/Embeddable.tsx#L28-L30

```tsx
    private rendering?: Promise<void>

	// ...

    async componentDidMount () {
        if(!this.rendering) {
            this.rendering = this.createAndRenderChart()
        }
    }
```

Setting the `rendering` field to be a promise seems a bit odd, and I'm not sure what the goal with it is. I'd think it would make more sense to use a boolean for this field, setting it to to when the rendering starts and false when it ends.

```tsx
    private rendering?: Promise<void>

	// ...

    async componentDidMount () {
        if(!this.rendering) {
            this.createAndRenderChart()
        }
    }

    async createAndRenderChart () {
        this.rendering = true
        const seatsio = await this.getSeatsio()
        const config = this.extractConfigFromProps()
        config.container = this.container.current
        this.chart = this.createChart(seatsio, config).render()
        if (this.props.onRenderStarted) {
            this.props.onRenderStarted(this.chart)
        }
        this.rendering = false
    }
```

Granted, in this case I'm also not sure if you ever need to set it to `false`. The way it's being handled right now, once it's set to a promise, even when that promise resolves it will still be truthy:

image

So I'm not exactly sure what the intention here, but it's a bit confusing at the very least.

**Pull request merged**
