### PR TITLE
Skip re-render if embedded script has not finished loading

### PR DESCRIPTION
**Pull request by samheutmaker**
@nahue  This is has been pretty thoroughly tested and works for my use case. I'm happy to implement any feedback, and thanks for building a kickass product.

### CODE REVIEW

**Comment by PabloNeirotti** [comment]
Hi Sam. Thank you for taking the time of writing this change.

There is a problem however, and that if two props change subsequently, the second one will be ignored under this scenario. This would cause unpredictable results on production.

Just to understand this PR better, what is the issue that you are looking to solve?

Thanks!

**Comment by samheutmaker** [comment]
@PabloNeirotti My issue is that the app I'm working on re-renders the SeatsIO components before they are completely done reloading. This causes the SeatsIO component to crash, as every time the component re-rendered, the entire SeatsIO script is destroyed and reloaded. 

> There is a problem however, and that if two props change subsequently, the second one will be ignored under this scenario. This would cause unpredictable results on production.

What exactly do you mean by subsequently? Subsequently to what? Each other? The initial render? I'm happy to fix this issue.

**Comment by PabloNeirotti** [comment]
I see. If that's the case then it needs fixing.

While ignoring some props changes will fix this issue, it will introduce another issue: rapidly changing props will end up with some prop changes not being reflected on the chart.

What I mean by this is something like the following sequence of events:

1. A chart is loaded
2. `showLegend` is set to `true`
3. Chart commences to re-render
4. `pricing` changes to another set of prices
5. Chart is done re-rendering

In the example above, pricing changes will be ignored since they were done during re-rendering, with these code changes.

Changing the HTML id of the chart to a unique value every time might fix this issue. I'd like to do some more digging myself to understand this issue better, and then get back to you. Feel free to try other methods!

Cheers!

**Comment by PabloNeirotti** [comment]
Hi @samheutmaker 

While we take a look at this, you might be able to solve your issue on your project by waiting until all of your requests are done, and then render the chart. You could display a loading indicator in the meantime to your users.

We might be able to solve this differently, like for instance allowing the embed in general (not just in React) to be destroyed at any time.

Please let me know if that would work.

Cheers!

**Comment by samheutmaker** [comment]
@PabloNeirotti This might work, but I don't think it's a longterm solution. I'm working on a fix for the issues you outlined above.

**Comment by mroloux** [comment]
Fixed by https://github.com/seatsio/seatsio-react/pull/14

**Pull request closed without merging**
