### PR TITLE
Convert to TypeScript and use seatsio-types

### PR DESCRIPTION
**Pull request by mortendevold**
This PR converts the project to TypeScript and implements `@seatsio/seatsio-types` 0.3.2. Tested in playground as well as `seatsio-webapp` with local "link:.." in package.json.

### CODE REVIEW

**Comment by mortendevold** [comment]
[Implement types in seatsio-react](https://trello.com/c/SSfgepOI/5802-implement-types-in-seatsio-react)

**Comment by mortendevold** [comment]
Playground also converted to TypeScript and made some improvements to dark mode:
image

**Comment by mroloux** [comment]
@mortendevold I'm getting this error in IntellIJ, in `App.tsx` of the playground project:

"TS7016: Could not find a declaration file for module  @seatsio/seatsio-react ."

Already did a `yarn install`. That didn't fix it.

**Comment by mroloux** [comment]
Oh wait, now it's this error:

**Comment by mortendevold** [comment]
I was seeing that same error, have you ran yarn in seatsio-react as well? I added some type packages

**Comment by mroloux** [comment]
Yeah, I even removed the `node_modules` folder.

**Comment by mortendevold** [comment]
I just installed the latest IntelliJ and opened the project there. Works as expected, so not sure what the difference is. Will try killing `node_modules` in both seatsio-react and playground and reinstall.

**Comment by mroloux** [comment]
Alright. I also did a `yarn build` in the root project.

**Comment by mortendevold** [comment]
Had some missing types in root package.json (probably after solving conflicts after merge from master). If you pull the latest, do the errors go away? See another issue though, I now get intellisense in VSCode, but not in IntelliJ. Investigating.

**Comment by mroloux** [comment]
Screenshot 2023-10-20 at 15 43 36

**Comment by mroloux** [comment]
> Had some missing types in root package.json (probably after solving conflicts after merge from master). If you pull the latest, do the errors go away? See another issue though, I now get intellisense in VSCode, but not in IntelliJ. Investigating.

Awesome, that fixed it 👍

**Comment by mortendevold** [comment]
> Screenshot 2023-10-20 at 15 43 36

Yeah, if you instead use `language={"en"}` it seems to provide suggestions

**Comment by mroloux** [comment]
Works like a charm 👍 👍 👍 

One question though: do we need Babel, Webpack and rimraf? What's the advantage over just running `tsc`?

**Comment by mortendevold** [comment]
> Works like a charm 👍 👍 👍
> 
> One question though: do we need Babel, Webpack and rimraf? What's the advantage over just running `tsc`?

TSC will only transpile into JavaScript, nothing more. If we want to focus on being a library that users will package on their own, I guess that is fine. Babel/Webpack handles minification, polyfills for older browsers etc. We might not need it for this small project, but I don't think it matters if we keep it. Rimraf is just a convenience package, cleaning the output folder before each build (essentially platform safe `rm -rf`, which also gives it its name)

**Comment by mroloux** [comment]
If we don't need Babel and Webpack I say we remove them - simpler is better, right? 😉 Then we don't need to keep upgrading the versions of those packages for example.

Our clients will be using a minifier anyways, when they're packaging our react lib in their app. Polyfills shouldn't be needed as far as I know - and if our customers really need them they can configure their own bundler to include them.

(I might be missing something obvious here of course, but I didn't see an immediate need for Babel/Webpack in this particular project, if we're on TS).

**Review by mroloux — APPROVED** [review]

**Comment by mortendevold** [comment]
I've moved the test to TypeScript, and now use `ts-jest` to run them. Seems to work well, so I've removed everything related to Webpack and Babel. We should consider if we want to ship each transpiled file in a `lib` folder in addition to the build bundle. That would allow importing just what you need by using for instance `import SeatsioSeatingChart from '@seatsio/seatsio-react/lib/SeatsioSeatingchart'`

**Comment by mroloux** [comment]
> seatsio/seatsio-react/lib/SeatsioSeatingchart

Yeah, that's something we could look into in a followup PR

**Comment by mortendevold** [comment]
Found that using just `tsc` to output a single file only allows AMD or SystemJS, which is not something we want. Will have to revert to using webpack to get a sensible module format. Currently running into an issue where types are not working, so looking into what's wrong.

**Comment by mroloux** [comment]
> Found that using just `tsc` to output a single file only allows AMD or SystemJS, which is not something we want. Will have to revert to using webpack to get a sensible module format. Currently running into an issue where types are not working, so looking into what's wrong.

Ok, but why does it need to be a single file? Does `tsc` not output JS files with standard JS modules?

**Comment by mortendevold** [comment]
> > Found that using just `tsc` to output a single file only allows AMD or SystemJS, which is not something we want. Will have to revert to using webpack to get a sensible module format. Currently running into an issue where types are not working, so looking into what's wrong.
> 
> Ok, but why does it need to be a single file? Does `tsc` not output JS files with standard JS modules?

Doesn't have to, we can of course create separate JS + .d.ts files. Right now the biggest issue is figuring out why type suggestions have gone out the window.

**Review by mroloux — APPROVED** [review]

**Pull request merged**
